name: hello world

on: [push]

jobs:
  build:
    name: hello world build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Install dependencies
        run: cd src/helloworld && dotnet restore
      - name: Build
        run: cd src/helloworld && dotnet build --configuration Release --no-restore
